feat: deserialize play packets
MierenManz/Blocktopus pull request #11
Opened 2023-04-11 02:52 UTC by lino-levan

I'm sorry, reviewing this is gonna suck

2023-04-11 07:05 UTC, MierenManz commented on redstone_serde/deserialize/play.ts
> +export function deserializeLoginPackets(
this should be `deserializePlayPackets` :P

2023-04-11 07:06 UTC, MierenManz commented on redstone_serde/deserialize/play.ts
> +function getPosition(reader: Reader) {
this functionality is already in `redstone_serde/util.ts`

2023-04-11 18:31 UTC, lino-levan commented
This should be good

2023-04-11 19:48 UTC, lino-levan commented
Closes #6

2023-04-12 15:45 UTC, MierenManz requested changes

2023-04-12 15:45 UTC, MierenManz commented on redstone_serde/deserialize/play.ts
> +    })).sort((a, b) => a.position - b.position).map(({ slot }) => slot),
Does this need to be sorted?

2023-04-12 15:45 UTC, MierenManz commented on redstone_serde/deserialize/play.ts
> +function pluginMessage(_reader: Reader): PluginMessagePayload {
Looked at this on the wiki and I don't think this will be necessary for us unless we want to intergrate with mods

2023-04-12 15:45 UTC, MierenManz commented on redstone_serde/deserialize/play.ts
> +    sneaking: !!reader.getInt8(),
missing optional hand field 
![image](https://user-images.githubusercontent.com/63878374/231504794-3ca469ad-9e5f-4649-b64b-10bcc4cfbabe.png)

2023-04-12 15:46 UTC, MierenManz commented
ffs wrong review status. Just wanted to comment for now. Let's discuss on discord when you have time

2023-04-12 15:47 UTC, MierenManz reviewed
.

2023-04-12 16:01 UTC, MierenManz commented on redstone_serde/deserialize/play.ts
> +    slots: new Array(reader.getVarInt()).fill(undefined).map(() => ({
As discussed on discord. Gonna add this in a follow up PR

2023-04-12 16:02 UTC, MierenManz commented on redstone_serde/deserialize/play.ts
> +    })).sort((a, b) => a.position - b.position).map(({ slot }) => slot),
As discussed on discord: Does not have to be sorted and will be rewritten a little in a follow up PR

2023-04-12 16:55 UTC, merged